name: Deploy Node.js API to EC2

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          cd api-chicorei-nodejs
          npm install

      - name: Rodar testes
        run: |
          cd api-chicorei-nodejs
          node src/test.js

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar acesso SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy na EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app

            if [ ! -d "api-chicorei-nodejs" ]; then
              git clone https://github.com/phfdias88/avaliacao-devops-cr.git api-chicorei-nodejs
            else
              cd api-chicorei-nodejs
              git pull origin main
            fi

            cd /home/ubuntu/app/api-chicorei-nodejs

            # Verificar se o package.json existe
            if [ ! -f package.json ]; then
              echo "Erro: package.json não encontrado!"
              exit 1
            fi

            # Instalar dependências
            npm install

            # Parar API antiga e rodar novamente
            pkill -f "node src/index.js" || true
            nohup node src/index.js > output.log 2>&1 &
          EOF
